version: "3.7"

services:
  web:
    image: webdevops/php-apache:8.1-alpine
    container_name: clients-crud
    tty: true
    ports:
      - "8000:80"
    working_dir: /app
    volumes:
      - ../../backend:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
    command: sh -c "composer install && /usr/bin/supervisord -c /opt/docker/etc/supervisor.conf --logfile /dev/null --pidfile /dev/null --user root"

    #    links:
    #      - database

    #  database:
    #    image: mysql:8.0
    #    container_name: MySQL
    #    restart: always
    #    ports:
    #      - "3306:3306"
    #    environment:
    #      MYSQL_ROOT_PASSWORD: root
    #      MYSQL_DATABASE: spaceships
    #    volumes:
    #      - data-bd:/var/lib/mysql
    #
    #volumes:
    #  data-bd: